ItemEvents.tooltip(event => {
    event.add("kubejs:basic_control_circuit", "§aULV級回路")
    event.add("kubejs:advanced_control_circuit", "§cLV級回路")
    event.add("kubejs:elite_control_circuit", "§bMV級回路")
    event.add("kubejs:ultimate_control_circuit", "§5HV級回路")
    event.add("kubejs:ultima_control_circuit", "§4EV級回路")
    event.add("kubejs:warped_ender_pearl", "スニークしながら右クリックで個人テレポート地点を設定、右クリックでその地点にテレポート")
    event.add("kubejs:hyper_stable_self_healing_adhesive", "§7選択的に完全接着し、裂けたり損傷しても有効")
    event.add("kubejs:black_body_naquadria_supersolid", "§7液体のように流れ、いかなる電磁波も反射せず、完全に吸収・伝達する")
    event.add("kubejs:command_wand", "左手にコマンドブロックを持ち、創造安定コアの上にのみ設置可能")
    event.add("kubejs:uruium_coil_block", ["超次元プラズマ鍛造炉に32000Kの炉温を提供可能", "恒星鍛造炉モードではこのコイルのみ使用可能"])
    event.add("kubejs:essence_block", "骨ブロックを変換室に設置して入手")
    event.add("kubejs:draconium_block_charged", "ドラゴンパワー注入黒曜石を変換室に設置して入手")
    event.add("minecraft:crimson_stem", "オークの原木を変換室に設置して入手")
    event.add("minecraft:warped_stem", "シラカバの原木を変換室に設置して入手")
    event.add("minecraft:bone_block", "カルシウムブロックを変換室に設置して入手")
    event.add("minecraft:moss_block", "草ブロックを変換室に設置して入手")
    event.add("minecraft:sculk", "苔ブロックを変換室に設置して入手")
    event.add("gtceu:magmatter_block", "1スタック以上の磁性物質インゴットを創造の門に投げ入れて入手")
    event.add("minecraft:command_block", "磁性流体拘束恒星物質ブロックを創造の門に投げ入れて入手")
    event.add("minecraft:chain_command_block", "チェーンコマンドブロックコアと壊れかけのコマンドブロックを合成して入手")
    event.add("minecraft:repeating_command_block", "リピートコマンドブロックコアと壊れかけのパルスコマンドブロックを合成して入手")
    event.add("ad_astra:oxygen_loader", "§cクラフト専用、酸素は生成されません")
})